name: Deploy Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Run Tests
        run: ./mvnw test

      - name: Build Application
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/logistics-tracker:${{ github.ref_name }} \
            .

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u ${{ github.actor }} \
            --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/logistics-tracker:${{ github.ref_name }}

      - name: Deploy Production
        run: |
          echo "Executar deploy produção aqui"